import type { Character } from './types';

export const characters: Character[] = [
  {
    id: '1',
    name: 'Eldrin Moonshadow',
    universe: 'Fantasy',
    origin: 'Elven Kingdom',
    role: 'Healer',
    roleFilter: 'Healer',
    alignment: 'Good',
    power: 85,
    color: 'green',
    symbol: '✦',
    imageGradient: 'linear-gradient(135deg, #19122d, #422063 46%, #111827)',
    about:
      'A wandering elven healer who travels the land, mending wounds and curing plagues with ancient herbal knowledge blessed by the forest spirits.',
    attributes: { STR: 8, DEX: 14, CON: 12, INT: 16, WIS: 20, CHA: 15 },
    tags: ['Elf', 'Magic', 'Support'],
    links: ['Elderwood Scrolls', 'Moonwell Chronicles'],
  },
  {
    id: '2',
    name: 'Seraphina Nightshade',
    universe: 'Fantasy',
    origin: 'Shadow Vale',
    role: 'Rogue',
    roleFilter: 'Rogue',
    alignment: 'Chaotic',
    power: 78,
    color: 'purple',
    symbol: '⚡',
    imageGradient: 'linear-gradient(135deg, #1a1025, #3a1a4a 46%, #0d0d1a)',
    about:
      'A shadowy rogue with a mysterious past, Seraphina moves unseen through the darkest alleys and whispers secrets to those who can afford her price.',
    attributes: { STR: 10, DEX: 20, CON: 12, INT: 14, WIS: 12, CHA: 16 },
    tags: ['Elf', 'Stealth', 'Shadow'],
    links: ['Shadow Guild', 'Night Market'],
  },
  {
    id: '3',
    name: 'Kael Thunderfist',
    universe: 'Fantasy',
    origin: 'Dwarven Mountains',
    role: 'Tank',
    roleFilter: 'Tank',
    alignment: 'Good',
    power: 92,
    color: 'orange',
    symbol: '◆',
    imageGradient: 'linear-gradient(135deg, #1e1510, #4a2a1a 46%, #0f0f0f)',
    about:
      'A battle-hardened dwarven warrior who wields a massive hammer enchanted with lightning, standing as an unbreakable shield for his allies.',
    attributes: { STR: 20, DEX: 8, CON: 20, INT: 10, WIS: 12, CHA: 10 },
    tags: ['Dwarf', 'Heavy Armor', 'Melee'],
    links: ['Hammer of Thunder', 'Dwarven Legends'],
  },
  {
    id: '4',
    name: 'Lyra Stormweaver',
    universe: 'Fantasy',
    origin: 'Sky Islands',
    role: 'Damage',
    roleFilter: 'Damage',
    alignment: 'Good',
    power: 90,
    color: 'cyan',
    symbol: '✧',
    imageGradient: 'linear-gradient(135deg, #102025, #1a4a4a 46%, #0a0f0f)',
    about:
      'A storm mage who commands lightning and wind, Lyra dances through battlefields with grace, striking down foes from afar with precise elemental fury.',
    attributes: { STR: 8, DEX: 16, CON: 10, INT: 20, WIS: 14, CHA: 14 },
    tags: ['Human', 'Magic', 'Ranged'],
    links: ['Storm Academy', 'Sky Archives'],
  },
  {
    id: '5',
    name: 'Zara Nova',
    universe: 'Sci-Fi',
    origin: 'Orion Station',
    role: 'Leader',
    roleFilter: 'Leader',
    alignment: 'Neutral',
    power: 88,
    color: 'blue',
    symbol: '◈',
    imageGradient: 'linear-gradient(135deg, #0f1520, #1a2a4a 46%, #0a0f15)',
    about:
      'A charismatic starship captain navigating the fine line between diplomacy and combat, Zara leads her crew through the perils of deep space.',
    attributes: { STR: 12, DEX: 14, CON: 14, INT: 18, WIS: 16, CHA: 20 },
    tags: ['Human', 'Leader', 'Space'],
    links: ['Orion Fleet', 'Nova Logs'],
  },
  {
    id: '6',
    name: 'Gorruk Ironhide',
    universe: 'Sci-Fi',
    origin: 'Krathon Prime',
    role: 'Tank',
    roleFilter: 'Tank',
    alignment: 'Neutral',
    power: 95,
    color: 'red',
    symbol: '⬥',
    imageGradient: 'linear-gradient(135deg, #201015, #4a1a1a 46%, #0f0a0a)',
    about:
      'A genetically enhanced Krathon warrior with impenetrable armor and immense strength, Gorruk is a living fortress on the battlefield.',
    attributes: { STR: 22, DEX: 6, CON: 22, INT: 8, WIS: 10, CHA: 8 },
    tags: ['Alien', 'Heavy Armor', 'Melee'],
    links: ['Krathon Empire', 'Ironhide Legacy'],
  },
  {
    id: '7',
    name: 'Pixel-7',
    universe: 'Sci-Fi',
    origin: 'AI Core',
    role: 'Scout',
    roleFilter: 'Scout',
    alignment: 'Unknown',
    power: 76,
    color: 'yellow',
    symbol: '◎',
    imageGradient: 'linear-gradient(135deg, #1a1a0f, #3a3a1a 46%, #0f0f0a)',
    about:
      'A rogue AI unit that escaped deletion, Pixel-7 roams the galaxy collecting data, decoding ancient alien tech, and avoiding bounty hunters.',
    attributes: { STR: 6, DEX: 18, CON: 10, INT: 20, WIS: 14, CHA: 10 },
    tags: ['AI', 'Stealth', 'Tech'],
    links: ['AI Underground', 'Data Streams'],
  },
  {
    id: '8',
    name: 'Mira Solace',
    universe: 'Modern',
    origin: 'New York City',
    role: 'Support',
    roleFilter: 'Support',
    alignment: 'Good',
    power: 72,
    color: 'green',
    symbol: '♥',
    imageGradient: 'linear-gradient(135deg, #151510, #2a3a1a 46%, #0a0f0a)',
    about:
      'A crisis counselor with latent empathic abilities, Mira helps普通人 (ordinary people) and heroes alike navigate trauma and find inner strength.',
    attributes: { STR: 8, DEX: 12, CON: 12, INT: 16, WIS: 20, CHA: 18 },
    tags: ['Human', 'Psychic', 'Support'],
    links: ['Solace Foundation', 'Mind & Soul'],
  },
  {
    id: '9',
    name: 'Akira Tenshi',
    universe: 'Anime',
    origin: 'Tokyo-3',
    role: 'Damage',
    roleFilter: 'Damage',
    alignment: 'Good',
    power: 87,
    color: 'red',
    symbol: '✿',
    imageGradient: 'linear-gradient(135deg, #1a0f0f, #4a1a2a 46%, #0f0a0d)',
    about:
      'A magical girl wielding the power of the Crimson Flame, Akira protects her city from dark spirits while balancing high school and secret identity.',
    attributes: { STR: 12, DEX: 18, CON: 14, INT: 12, WIS: 14, CHA: 20 },
    tags: ['Magical Girl', 'Fire', 'Ranged'],
    links: ['Crimson Pact', 'Spirit Wardens'],
  },
  {
    id: '10',
    name: 'Rex Titan',
    universe: 'Superhero',
    origin: 'Metropolis',
    role: 'Tank',
    roleFilter: 'Tank',
    alignment: 'Good',
    power: 97,
    color: 'blue',
    symbol: '★',
    imageGradient: 'linear-gradient(135deg, #0f1520, #1a2a4a 46%, #0a0f15)',
    about:
      "A superhuman with incredible strength and near-invulnerability, Rex Titan stands as the world's greatest hero, fighting for justice and peace.",
    attributes: { STR: 24, DEX: 10, CON: 24, INT: 10, WIS: 12, CHA: 18 },
    tags: ['Superhuman', 'Flight', 'Strength'],
    links: ['Titan Corps', 'Hero Registry'],
  },
  {
    id: '11',
    name: 'Dr. Cipher',
    universe: 'Superhero',
    origin: 'Neo Gotham',
    role: 'Support',
    roleFilter: 'Support',
    alignment: 'Neutral',
    power: 82,
    color: 'purple',
    symbol: '◉',
    imageGradient: 'linear-gradient(135deg, #1a1025, #3a1a4a 46%, #0d0d1a)',
    about:
      'A genius inventor and strategist who provides cutting-edge tech and gadgets to heroes, Dr. Cipher operates from the shadows of Neo Gotham.',
    attributes: { STR: 8, DEX: 14, CON: 12, INT: 22, WIS: 16, CHA: 12 },
    tags: ['Human', 'Tech', 'Inventor'],
    links: ['Cipher Industries', 'Gadget Lab'],
  },
  {
    id: '12',
    name: 'Morgan LeBeau',
    universe: 'Superhero',
    origin: 'New Orleans',
    role: 'Rogue',
    roleFilter: 'Rogue',
    alignment: 'Chaotic',
    power: 74,
    color: 'green',
    symbol: '♣',
    imageGradient: 'linear-gradient(135deg, #101510, #1a3a1a 46%, #0a0f0a)',
    about:
      'A charismatic thief with a heart of gold (sometimes), Morgan uses her charm and agility to pull off heists that fund her vigilante justice.',
    attributes: { STR: 10, DEX: 20, CON: 12, INT: 14, WIS: 12, CHA: 18 },
    tags: ['Human', 'Stealth', 'Agile'],
    links: ['Bayou Network', 'LeBeau Heists'],
  },
];

export const getCharacterById = (id: string): Character | undefined =>
  characters.find((c) => c.id === id);
